<?php

namespace app\models;


use Yii;
use \yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "partners".
 *
 * @property int $id
 * @property string $image
 * @property string $link
 */
class Partners extends ActiveRecord {

    public $image_;
    public $ignoreAfterSave = false;

    public static function tableName()
    {
        return 'partners';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['image', 'link'], 'default', 'value' => ''],
            [['image', 'link'], 'string', 'max' => 200],
            [['name'], 'string', 'max' => 50],
            [['image_'], 'safe'],
            [['image_'], 'file', 'extensions' => 'jpg, gif, png'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id'        => 'ID',
            'image'     => 'Картинка',
            'link'      => 'Ссылка',
            'name'      => 'Партнер',
            'image_'    => 'Картинка'
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->ignoreAfterSave) {
            parent::beforeSave($insert);
            return true;
        }

        $path = Yii::getAlias('@web') . 'images/partners/';
        $title_image = UploadedFile::getInstance($this, 'image_');

        if ($title_image) {
            if ($this->image != null) {
                $files = FileHelper::findFiles($path);
                foreach ($files as $file) {
                    if (pathinfo($file, PATHINFO_BASENAME) ==
                        pathinfo($this->image, PATHINFO_BASENAME)) {
                        $path_delete_file = Yii::getAlias('@web') . pathinfo($file, PATHINFO_DIRNAME)
                            . '/' . pathinfo($file, PATHINFO_BASENAME);

                        FileHelper::unlink($path_delete_file);
                        break;
                    }
                }
            }

            $this->image = '/images/partners/' . $title_image->name;

            Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web';
            $path_save = Yii::$app->params['uploadPath'] . $this->image;

            $title_image->saveAs($path_save);
        }

//        debug('=> beforeSave() <=');
//        debug($this);
//        exit;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $path = Yii::getAlias('@web') . 'images/partners/';

        if ($this->image) {
            $files = FileHelper::findFiles($path);
            foreach ($files as $file) {
                if (pathinfo($file, PATHINFO_BASENAME) ==
                    pathinfo($this->image, PATHINFO_BASENAME)) {
                    $path_delete_file = Yii::getAlias('@web') . pathinfo($file, PATHINFO_DIRNAME)
                        . '/' . pathinfo($file, PATHINFO_BASENAME);

                    FileHelper::unlink($path_delete_file);
                    break;
                }
            }
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

}
