<?php

namespace app\models;


use Yii;
use yii\db\ActiveRecord;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string $name
 * @property string $image
 * @property string $profession
 * @property string $experience
 */

class Team extends ActiveRecord
{
    public $photo;
    public $ignoreAfterSave = false;

    public static function tableName()
    {
        return 'team';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['profession', 'experience'], 'default', 'value' => ''],
            [['profession', 'experience'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['image'], 'string', 'max' => 200],
            [['photo'], 'safe'],
            [['photo'], 'file', 'extensions' => 'jpg, gif, png'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id'            => 'ID',
            'name'          => 'Имя',
            'image'         => 'Фото',
            'profession'    => 'Профессия',
            'experience'    => 'Опыт',
            'photo'         => 'Фото'
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->ignoreAfterSave) {
            parent::beforeSave($insert);
            return true;
        }

        $path = Yii::getAlias('@web') . 'images/team/';
        $title_image = UploadedFile::getInstance($this, 'photo');

        if ($title_image) {
            if ($this->image != null) {
                $files = FileHelper::findFiles($path);
                foreach ($files as $file) {
                    if (pathinfo($file, PATHINFO_BASENAME) ==
                        pathinfo($this->image, PATHINFO_BASENAME)) {
                        $path_delete_file = Yii::getAlias('@web') . pathinfo($file, PATHINFO_DIRNAME)
                            . '/' . pathinfo($file, PATHINFO_BASENAME);

                        FileHelper::unlink($path_delete_file);
                        break;
                    }
                }
            }

            $this->image = '/images/team/' . $title_image->name;

            Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web';
            $path_save = Yii::$app->params['uploadPath'] . $this->image;

            $title_image->saveAs($path_save);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $path = Yii::getAlias('@web') . 'images/team/';

        if ($this->image) {
            $files = FileHelper::findFiles($path);
            foreach ($files as $file) {
                if (pathinfo($file, PATHINFO_BASENAME) ==
                    pathinfo($this->image, PATHINFO_BASENAME)) {
                    $path_delete_file = Yii::getAlias('@web') . pathinfo($file, PATHINFO_DIRNAME)
                        . '/' . pathinfo($file, PATHINFO_BASENAME);

                    FileHelper::unlink($path_delete_file);
                    break;
                }
            }
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

}
